server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # Hotel Service
        - id: hotel-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/hotels/**, /api/rooms/**, /api/hotel/**
          filters:
            - StripPrefix=1

        # Booking Service
        - id: booking-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/bookings/**, /api/admin/users/**, /api/booking/test/**
          filters:
            - StripPrefix=1

        # Auth Service
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        # Публичные endpoints
        - id: public-endpoints
          uri: http://localhost:8084
          predicates:
            - Path=/public/**, /actuator/health, /h2-console/**

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO