server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # Улучшенная конфигурация маршрутов
      routes:
        # Маршрут для Hotel Service
        - id: hotel-service-hotels
          uri: http://localhost:8081
          predicates:
            - Path=/api/hotels/**
          filters:
            - StripPrefix=1  # Убирает /api из пути

        # Маршрут для Hotel Service (комнаты)
        - id: hotel-service-rooms
          uri: http://localhost:8081
          predicates:
            - Path=/api/rooms/**
          filters:
            - StripPrefix=1  # Убирает /api из пути

        # Маршрут для Booking Service
        - id: booking-service-test
          uri: http://localhost:8082
          predicates:
            - Path=/api/test/**
          filters:
            - StripPrefix=1  # Убирает /api из пути

        - id: booking-service-auth
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1  # Убирает /api из пути

        - id: booking-service-booking
          uri: http://localhost:8082
          predicates:
            - Path=/api/bookings/**
          filters:
            - StripPrefix=1  # Убирает /api из пути

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG