server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin123

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO